### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Laukau** [viipu/Linkkikirjasto-Tsoha#1]
Projekti ladattu 3.1.2016 klo. 11.30
Sivujen painikkeisiin voisi lisätä linkit toimiviin sivuihin, kuten lainojen ja aineiston listaukseen sekä kurssin esittelysivulle (myöskään tiedoston README.md linkki aineiston sivulle ei toiminut). Koodi näyttää siistiltä ja MVC-mallin mukaiselta, tosin joissakin kommenteissa puhutaan peleistä. Kontrollerin items_controller viimeiset metodit (metodista items_list lähtien) ovat ilmeisesti jääneet suunnitteluvaiheesta mutta joka tapauksessa ne vaikuttavat ylimääräisiltä tai olevan väärässä kontrollerissa. Kaikki on johdonmukaisesti englanniksi ja asiat on muutenkin nimetty selkeästi ja kuvaavasti. Lisäksi itse katselmointi oli helppo tehdä kun näkymissä muun muassa ilmoitettiin, minkä asioiden ei ole vielä tarkoitus toimia.

**Comment by viipu** [comment]
Kiitos paljon tarkkasilmäisestä katselmuksesta! Lisäilin/korjailin linkkejä ja siivoilin kommentteja, ja tosiaan tuonne kontrolleriin unohtuneita metodeja. Navipalkki on kyllä edelleen vähän vajavainen.
